### ISSUE TITLE
init() required?

### ISSUE THREAD

**Issue by eccles** [KimMachineGun/automemlimit#20]
Can you clarify whether it is required to put this code in an init() method?

**Comment by KimMachineGun** [comment]
There are two ways to use this library in your codebase.

The first way, the simple one, needs one line of code in your import block. It will configure the memory limit with environment variables and some default options. (It uses `init` function internally)

```go
import _ "github.com/KimMachineGun/automemlimit"
```

The second way is for the more advanced configuration (and might be relevant to your question).

In this case, you should write a few lines of code; where to put it does not matter. Although the usual place to put this kind of runtime configuration code is inside of the `init` function (or entry point of your program), you could write it in another place (such as HTTP handler) based on your situation, and it is perfectly fine.

\+ However, since it has certain overheads, I recommend not writing this code in your program's critical path.

```go
memlimit.SetGoMemLimitWithOpts(k
	memlimit.WithRatio(0.9),
	memlimit.WithProvider(memlimit.FromCgroup),
	memlimit.WithLogger(slog.Default()),
)
```

**Comment by eccles** [comment]
Thank you for your help - much appreciated.
